env:
  browser: true
  webextensions: true
  jquery: true
  es6: true
  es2024: true

overrides:
  - files:
      - "**/*.mjs"
    parserOptions:
      sourceType: module

globals:
  __OdooTerminal: readonly
  _: off
  moment: readonly
  odoo: readonly
  owl: readonly
  openerp: off

rules:
  eqeqeq: 2
  no-empty-function: 2
  no-eval: 2
  no-implicit-coercion: 2
  no-implicit-globals: 2
  no-implied-eval: 2
  no-return-assign: 2
  no-undef-init: 2
  no-shadow: 2
  no-script-url: 2
  no-unneeded-ternary: 2
  no-unused-expressions: 2
  no-labels: 2
  no-useless-call: 2
  no-useless-computed-key: 2
  no-useless-concat: 2
  no-useless-constructor: 2
  no-useless-rename: 2
  no-useless-return: 2
  no-void: 2
  prefer-const: 2
  prefer-numeric-literals: 2
  prefer-object-has-own: 2
  spaced-comment: 2
  radix: 2
  prefer-arrow-callback: 1
  no-var: 1
  no-extra-bind: 1
  no-lone-blocks: 1

extends:
  - eslint:recommended
  - plugin:prettier/recommended
