# Defaults for all prettier-supported languages.
# Prettier will complete this with settings from .editorconfig file.
printWidth: 80
tabWidth: 2
semi: true
singleQuote: true
quoteProps: "as-needed"
jsxSingleQuote: false
trailingComma: "all"
bracketSpacing: false
bracketSameLine: false
arrowParens: "avoid"
requirePragma: false
proseWrap: always
htmlWhitespaceSensitivity: "css"
vueIndentScriptAndStyle: false
endOfLine: "lf"
embeddedLanguageFormatting: "auto"
singleAttributePerLine: false
