os: linux
dist: xenial
language: python
cache:
  directories:
    - $HOME/.cache/pip

python:
  - "3.8"

addons:
  apt:
    packages:
      - expect-dev # provides unbuffer utility

stages:
  - pre-commit
  - selenium

jobs:
  include:
    - stage: pre-commit
      name: "eslint, web-ext, prettier, etc..."
      node_js:
        - node
      cache:
        directories:
          - $HOME/.cache/pre-commit
      install:
        - pip install pre-commit
      script:
        - pre-commit run --all --show-diff-on-failure --verbose --color always
    - stage: selenium
      name: "Chrome"
      services:
        - xvfb
      cache:
        directories:
          - $HOME/.wdm
      addons:
        chrome: stable
      install:
        - pip install -r tests/requirements.txt
        - pip install -r tools/requirements.txt
      before_script:
        - export DISPLAY=:99.0
        - python3 tools/release.py
      script:
        - python3 -m unittest tests.test_chrome
    - stage: selenium
      name: "Firefox"
      services:
        - xvfb
      cache:
        directories:
          - $HOME/.wdm
      addons:
        firefox: latest
      install:
        - pip install -r tests/requirements.txt
        - pip install -r tools/requirements.txt
      before_script:
        - export DISPLAY=:99.0
        - python3 tools/release.py
      script:
        - python3 -m unittest tests.test_firefox
